# A sample Supabase configuration file for local development
# This file configures the Supabase local development environment

# Project settings
project_id = "lumea-coaching"

[api]
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "http://localhost:5173",
  "http://localhost:8080",
  "http://localhost:8081", 
  "http://localhost:8082",
  "http://localhost:8083",
  "http://localhost:8084",
  "http://localhost:8085",
  "https://localhost:5173",
  "https://localhost:8080"
]
# autoconfirm = true # Set to false to require email confirmation
jwt_expiry = 3600
enable_signup = true

# Comment out storage section to avoid parsing errors
# [storage]
# Define buckets properly

# Feature flags
[analytics]
enabled = false

# [experimental]
# minimal_service = false 