name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci --workspaces --if-present
      
      # Install required dependencies explicitly
      - name: Install required dependencies
        run: npm install --save-dev vite-plugin-compression2 rollup-plugin-visualizer
      
      # Run linting and apply auto-fixes
      - name: Run ESLint
        run: npm run lint -- --fix

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci --workspaces --if-present
      
      # Install required dependencies explicitly
      - name: Install required dependencies
        run: npm install --save-dev vite-plugin-compression2 rollup-plugin-visualizer
      
      # Run type checking
      - name: Run type checking
        run: npm run ci-check
      
      # Build the application
      - name: Build application
        run: npm run build --if-present

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci --workspaces --if-present
      
      # Run tests
      - name: Run tests
        run: npm test
