name: Snyk Security Scanning (Optional)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

jobs:
  snyk-security:
    name: Snyk Security Analysis
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if Snyk token is available
        id: check-snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "Snyk token not available, skipping Snyk security scans"
          fi

      - name: Setup Node.js
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        if: steps.check-snyk.outputs.enabled == 'true'
        run: npm ci --workspaces --if-present

      - name: Run Snyk to check for vulnerabilities
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --all-projects
          command: test

      - name: Run Snyk to check for open source vulnerabilities
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --all-projects --json
          command: test
        continue-on-error: true

      - name: Upload Snyk results to GitHub Code Scanning
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  snyk-container:
    name: Snyk Container Security
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if Snyk token is available
        id: check-snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "Snyk token not available, skipping Snyk container scans"
          fi

      - name: Check for Dockerfiles
        if: steps.check-snyk.outputs.enabled == 'true'
        id: check-docker
        run: |
          if find . -name "Dockerfile*" -type f | grep -q .; then
            echo "dockerfiles=true" >> $GITHUB_OUTPUT
          else
            echo "dockerfiles=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Snyk to check Docker images for vulnerabilities
        if: steps.check-snyk.outputs.enabled == 'true' && steps.check-docker.outputs.dockerfiles == 'true'
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: .
          args: --severity-threshold=high

  snyk-iac:
    name: Snyk Infrastructure as Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if Snyk token is available
        id: check-snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "Snyk token not available, skipping Snyk IaC scans"
          fi

      - name: Run Snyk to check for IaC vulnerabilities
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium

  snyk-monitor:
    name: Snyk Monitor (Track Dependencies)
    runs-on: ubuntu-latest
    # Only run on main branch
    if: ${{ github.ref == 'refs/heads/main' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if Snyk token is available
        id: check-snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "Snyk token not available, skipping Snyk monitoring"
          fi

      - name: Setup Node.js
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        if: steps.check-snyk.outputs.enabled == 'true'
        run: npm ci --workspaces --if-present

      - name: Monitor dependencies with Snyk
        if: steps.check-snyk.outputs.enabled == 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects 