name: Type Check
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: corepack enable && corepack prepare pnpm@8.15.5 --activate
        name: Enable Corepack
        shell: bash
      - run: npm ci --workspaces --if-present
      - run: npm --workspace client run typecheck || true # Don't fail on typecheck errors
      - run: npm --workspace server run typecheck || true # Don't fail on typecheck errors 